const RANDOM_MEAL = 'RANDOM_MEAL';
const LIST_MEAL = 'LIST_MEAL';
const LIST_CATEGORIES = 'LIST_CATEGORIES';
const LIST_COUNTRIES = 'LIST_COUNTRIES';
const LIST_DESSERT = 'LIST_DESSERT';
const CHANGE_CATEGORY = 'CHANGE_CATEGORY';

export {
  RANDOM_MEAL,
  LIST_MEAL,
  LIST_CATEGORIES,
  LIST_COUNTRIES,
  LIST_DESSERT,
  CHANGE_CATEGORY,
};
